---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: pr-nginx-3
  namespace: argocd
spec:
  destination:
    namespace: pr-nginx-3
    server: https://kubernetes.default.svc
  project: previews
  source:
    helm:
      values: |
        image:
          tag: "1.15.0"
        ingress:
          host: "pr-nginx-3.localhost"
      version: v3
    path: helm
    repoURL: https://github.com/j2tlsk/nginx.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
